<?php

require_once '../bootstrap.php';

$dbc = new PDO('mysql:host=' . $_ENV['DB_HOST'] . ';dbname=' . $_ENV['DB_NAME'], $_ENV['DB_USER'], $_ENV['DB_PASS']);

$dbc->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
echo $dbc->getAttribute(PDO::ATTR_CONNECTION_STATUS) . "\n";

/*ads table*/
$dropTable = 'DROP TABLE IF EXISTS ads';

$dbc->exec($dropTable);

/*For ads table, create the query and assign to var*/
$createTable = "CREATE TABLE ads (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(100),
    vendor VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    zip VARCHAR(100),
    category VARCHAR(100),
    style  VARCHAR(100),
    origin VARCHAR(100),
    vintage INT,
    price DECIMAL(10, 2),
    description TEXT,
    image VARCHAR(100),
    PRIMARY KEY (id)
)";

$dbc->exec($createTable);

/*users table*/
$drop2 = 'DROP TABLE IF EXISTS users';
$dbc->exec($drop2);

/*For users table, create the query and assign to var; date_created will be auto generated by forms as a string so VARCHAR data type*/
$createUserTable = "CREATE TABLE IF NOT EXISTS users (
            user_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
            username VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            age INT(3) NOT NULL,
            PRIMARY KEY (user_id)
        )";                    

$dbc->exec($createUserTable);

?>

